// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iitd.assistech.mavi.domain;

import iitd.assistech.mavi.domain.SignBoardDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SignBoardDataOnDemand_Roo_Configurable {
    
    declare @type: SignBoardDataOnDemand: @Configurable;
    
}
